### ISSUE TITLE
`json.vegetable.as[Option[String]]` fails if the field is not present

### ISSUE THREAD

**Issue by jedesah** [propensive/rapture-json#48]
If works correctly if the field is present and the value is null, but fails if the field is not present, which is what is going to be the case 90% of the time.

**Comment by propensive** [comment]
Thanks for reporting this, @jedesah. It's actually a duplicate of #23. I've been working for a while on a rewrite of this part of the extraction system (which will also incorporate another couple of improvements), and I'm hoping to have a working version released in a couple of weeks.

Closing this issue as a duplicate.

**Comment by jedesah** [comment]
Oh, okay, cool. I had a look at other bugs, but did not find this one for some reason, sorry about that.
