### ISSUE TITLE
Error with Json example.

### ISSUE THREAD

**Issue by wpoosanguansit** [propensive/rapture-json#51]
Hi,

I am trying out the library and just try to follow the example in the documentation.  However, I get this error:

value json is not a member of StringContext

Which I believe is from some implicit conversion that I would need to import.  However, I do not know which.  Also I looked at the test file I found for the json code.  I have copied 

import rapture.core._
import rapture.json._
import rapture.data._

which are found in the file but that did not resolve the issue still.

Thanks for your help.

**Comment by ninowalker** [comment]
:+1: Same problem; I can import the dependencies, but no luck.

Sorry I'm a Scala noob.

**Comment by propensive** [comment]
Sorry that error message isn't particularly informative! You will need to specify which JSON backend you're using, e.g.
```
import rapture.json.jsonBackends.jawn._
```
or
```
import rapture.json.jsonBackends.spray._
```

**Comment by ninowalker** [comment]
Works for me! Thank you.

```
scala> import rapture.json.jsonBackends.jawn._
import rapture.json.jsonBackends.jawn._

scala> import rapture.json._
import rapture.json._

scala> json"""{}"""
res1: rapture.json.Json = {}

```
